In [2]:
import pandas as pd
ecg_df = pd.read_parquet("/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_ecg_20211105_df_w_episode_order.parquet")
ecg_df

,patient_id,ecg_id,ecg_acquisition_time,episode_id,eligibility_time
0,219126,407be100-3b36-11dc-4823-000206d60029,2007-07-25 23:02:25,219126_1,2007-07-25 23:59:59
1,219126,b44d0080-71ed-11dc-4823-00102de50029,2007-10-03 14:11:31,219126_2,2007-10-11 23:59:59
2,219126,ee6b9780-6f8c-11dc-4823-003316050029,2007-09-30 13:33:47,219126_2,2007-10-11 23:59:59
3,111471,d6670380-23f2-11dc-4823-0001f7ba0029,2007-06-24 22:47:40,111471_1,2007-07-05 23:59:59
4,111471,6740dd80-23f9-11dc-4823-0009f2c00029,2007-06-26 08:18:48,111471_1,2007-07-05 23:59:59
...,...,...,...,...,...
2257520,63468,38112300-6aec-11eb-4823-137cabd00029,2021-02-09 08:28:10,None,2021-02-09 08:28:10
2257521,35988,b29fec80-7070-11eb-4823-13a09a5a0029,2021-02-16 08:58:53,None,2021-02-16 08:58:53
2257522,65622,94eb7f80-0425-11ec-4823-146f52690029,2021-08-23 09:14:16,None,2021-08-23 09:14:16
2257523,70849,6db37100-4f6e-11eb-4823-23d054f30029,2021-01-05 08:49:24,None,2021-01-05 08:49:24
2257524,70526,3a381c00-a463-11eb-4823-34623fec0029,2021-04-23 12:33:40,None,2021-04-23 12:33:40

In [3]:
dad_df = pd.read_parquet("/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_dad_20211105_w_episode_order.parquet")
ed_df = pd.read_parquet("/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_ed_20211105_w_episode_order.parquet")

In [5]:
ed_df

,PATID,VISIT_DATE_DT,DXCODE1,DXCODE2,DXCODE3,DXCODE4,DXCODE5,DXCODE6,DXCODE7,DXCODE8,...,PROCCODE2,PROCCODE3,PROCCODE4,PROCCODE5,PROCCODE6,PROCCODE7,PROCCODE8,PROCCODE9,PROCCODE10,episode_order
0,4792,2021-05-20,E8310,C911,,,,,,,...,,,,,,,,,,4792_20
1,11405,2021-05-26,R104,,,,,,,,...,,,,,,,,,,11405_157
2,19828,2021-05-19,R060,E149,,,,,,,...,,,,,,,,,,19828_14
3,48054,2021-05-24,R060,E119,,,,,,,...,3JY20WC,,,,,,,,,48054_15
4,57490,2021-05-26,M2557,,,,,,,,...,,,,,,,,,,57490_21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3734770,294022,2010-02-27,R073,,,,,,,,...,,,,,,,,,,294022_6
3734771,295471,2009-02-15,S002,S050,W2209,U989,E119,,,,...,,,,,,,,,,295471_1
3734772,295471,2009-07-17,Z512,,,,,,,,...,,,,,,,,,,295471_2
3734773,295471,2009-09-27,Z512,,,,,,,,...,,,,,,,,,,295471_3
3734774,295471,2009-10-15,E1464,,,,,,,,...,,,,,,,,,,295471_4

In [3]:
import pandas as pd

temp = pd.read_parquet("/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_episode_df_all.parquet")
temp

          PATID episode_order type start_date   end_date duration
0        142962      142962_1   er 2015-01-26 2015-01-27   1 days
1        142962      142962_2  inp 2019-05-24 2019-05-26   2 days
2        142962      142962_3  inp 2019-05-29 2019-06-02   4 days
3        126949      126949_1   er 2007-08-28 2007-08-28   0 days
4        126949      126949_2   er 2011-07-19 2011-07-19   0 days
...         ...           ...  ...        ...        ...      ...
3437491  188186      188186_1   er 2009-09-03 2009-09-03   0 days
3437492  188186      188186_2   er 2009-09-18 2009-09-18   0 days
3437493  188186      188186_3   er 2013-08-26 2013-08-26   0 days
3437494  188186      188186_4  inp 2014-07-15 2014-07-18   3 days
3437495  188186      188186_5  inp 2019-05-21 2019-07-18  58 days

[3437496 rows x 6 columns]

In [ ]:
ls /data/padmalab_external/special_project/meds_pipeline_output/ahs/ahs_ecg_hosp_ed_linkage.parquet

ahs_admissions_meds_core.parquet    ahs_meds_core_part_0960.parquet
ahs_demographics_meds_core.parquet  ahs_meds_core_part_0961.parquet
ahs_diagnosis_meds_core.parquet     ahs_meds_core_part_0962.parquet
ahs_ecgs_meds_core.parquet          ahs_meds_core_part_0963.parquet
ahs_eds_meds_core.parquet           ahs_meds_core_part_0964.parquet
ahs_medicines_meds_core.parquet     ahs_meds_core_part_0965.parquet
ahs_meds_core_by_patient/           ahs_meds_core_part_0966.parquet
ahs_meds_core.parquet               ahs_meds_core_part_0967.parquet
ahs_meds_core_part_0001.parquet     ahs_meds_core_part_0968.parquet
ahs_meds_core_part_0002.parquet     ahs_meds_core_part_0969.parquet
ahs_meds_core_part_0003.parquet     ahs_meds_core_part_0970.parquet
ahs_meds_core_part_0004.parquet     ahs_meds_core_part_0971.parquet
ahs_meds_core_part_0005.parquet     ahs_meds_core_part_0972.parquet
ahs_meds_core_part_0006.parquet     ahs_meds_core_part_0973.parquet
ahs_meds_core_part_0007.parquet     ahs_meds_core_part_0974.parquet
ahs_meds_core_part_0008.parquet     ahs_meds_core_part_0975.parquet
ahs_meds_core_part_0009.parquet     ahs_meds_core_part_0976.parquet
ahs_meds_core_part_0010.parquet     ahs_meds_core_part_0977.parquet
ahs_meds_core_part_0011.parquet     ahs_meds_core_part_0978.parquet
ahs_meds_core_part_0012.parquet     ahs_meds_core_part_0979.parquet
ahs_meds_core_part_0013.parquet     ahs_meds_core_part_0980.parquet
ahs_meds_core_part_0014.parquet     ahs_meds_core_part_0981.parquet
ahs_meds_core_part_0015.parquet     ahs_meds_core_part_0982.parquet
ahs_meds_core_part_0016.parquet     ahs_meds_core_part_0983.parquet
ahs_meds_core_part_0017.parquet     ahs_meds_core_part_0984.parquet
ahs_meds_core_part_0018.parquet     ahs_meds_core_part_0985.parquet
ahs_meds_core_part_0019.parquet     ahs_meds_core_part_0986.parquet
ahs_meds_core_part_0020.parquet     ahs_meds_core_part_0987.parquet
ahs_meds_core_part_0021.parquet     ahs_meds_core_part_0988.parquet
ahs_meds_core_part_0022.parquet     ahs_meds_core_part_0989.parquet
ahs_meds_core_part_0023.parquet     ahs_meds_core_part_0990.parquet
ahs_meds_core_part_0024.parquet     ahs_meds_core_part_0991.parquet
ahs_meds_core_part_0025.parquet     ahs_meds_core_part_0992.parquet
ahs_meds_core_part_0026.parquet     ahs_meds_core_part_0993.parquet
ahs_meds_core_part_0027.parquet     ahs_meds_core_part_0994.parquet
ahs_meds_core_part_0028.parquet     ahs_meds_core_part_0995.parquet
ahs_meds_core_part_0029.parquet     ahs_meds_core_part_0996.parquet
ahs_meds_core_part_0030.parquet     ahs_meds_core_part_0997.parquet
ahs_meds_core_part_0031.parquet     ahs_meds_core_part_0998.parquet
ahs_meds_core_part_0032.parquet     ahs_meds_core_part_0999.parquet
ahs_meds_core_part_0033.parquet     ahs_meds_core_part_1000.parquet
ahs_meds_core_part_0034.parquet     ahs_meds_core_part_1001.parquet
ahs_meds_core_part_0035.parquet     ahs_meds_core_part_1002.parquet
ahs_meds_core_part_0036.parquet     ahs_meds_core_part_1003.parquet
ahs_meds_core_part_0037.parquet     ahs_meds_core_part_1004.parquet
ahs_meds_core_part_0038.parquet     ahs_meds_core_part_1005.parquet
ahs_meds_core_part_0039.parquet     ahs_meds_core_part_1006.parquet
ahs_meds_core_part_0040.parquet     ahs_meds_core_part_1007.parquet
ahs_meds_core_part_0041.parquet     ahs_meds_core_part_1008.parquet
ahs_meds_core_part_0042.parquet     ahs_meds_core_part_1009.parquet
ahs_meds_core_part_0043.parquet     ahs_meds_core_part_1010.parquet
ahs_meds_core_part_0044.parquet     ahs_meds_core_part_1011.parquet
ahs_meds_core_part_0045.parquet     ahs_meds_core_part_1012.parquet
ahs_meds_core_part_0046.parquet     ahs_meds_core_part_1013.parquet
ahs_meds_core_part_0047.parquet     ahs_meds_core_part_1014.parquet
ahs_meds_core_part_0048.parquet     ahs_meds_core_part_1015.parquet
ahs_meds_core_part_0049.parquet     ahs_meds_core_part_1016.parquet
ahs_meds_core_part_0050.parquet     ahs_meds_core_part_1017.parquet
ahs_meds_core_part_0051.parquet     ahs_meds_core_part_1018.parquet
ahs_meds_core_part_0052.parquet     ahs_meds_core_part_1019.parquet
ahs_meds_core_part_0053.parquet     ahs_meds_core_part_1020.parquet
ahs_meds_core_part_0054.parquet     ahs_meds_core_part_1021.parquet
ahs_meds_core_part_0055.parquet     ahs_meds_core_part_1022.parquet
ahs_meds_core_part_0056.parquet     ahs_meds_core_part_1023.parquet
ahs_meds_core_part_0057.parquet     ahs_meds_core_part_1024.parquet
ahs_meds_core_part_0058.parquet     ahs_meds_core_part_1025.parquet
ahs_meds_core_part_0059.parquet     ahs_meds_core_part_1026.parquet
ahs_meds_core_part_0060.parquet     ahs_meds_core_part_1027.parquet
ahs_meds_core_part_0061.parquet     ahs_meds_core_part_1028.parquet
ahs_meds_core_part_0062.parquet     ahs_meds_core_part_1029.parquet
ahs_meds_core_part_0063.parquet     ahs_meds_core_part_1030.parquet
ahs_meds_core_part_0064.parquet     ahs_meds_core_part_1031.parquet
ahs_meds_core_part_0065.parquet     ahs_meds_core_part_1032.parquet
ahs_meds_core_part_0066.parquet     ahs_meds_core_part_1033.parquet
ahs_meds_core_part_0067.parquet     ahs_meds_core_part_1034.parquet
ahs_meds_core_part_0068.parquet     ahs_meds_core_part_1035.parquet
ahs_meds_core_part_0069.parquet     ahs_meds_core_part_1036.parquet
ahs_meds_core_part_0070.parquet     ahs_meds_core_part_1037.parquet
ahs_meds_core_part_0071.parquet     ahs_meds_core_part_1038.parquet
ahs_meds_core_part_0072.parquet     ahs_meds_core_part_1039.parquet
ahs_meds_core_part_0073.parquet     ahs_meds_core_part_1040.parquet
ahs_meds_core_part_0074.parquet     ahs_meds_core_part_1041.parquet
ahs_meds_core_part_0075.parquet     ahs_meds_core_part_1042.parquet
ahs_meds_core_part_0076.parquet     ahs_meds_core_part_1043.parquet
ahs_meds_core_part_0077.parquet     ahs_meds_core_part_1044.parquet
ahs_meds_core_part_0078.parquet     ahs_meds_core_part_1045.parquet
ahs_meds_core_part_0079.parquet     ahs_meds_core_part_1046.parquet
ahs_meds_core_part_0080.parquet     ahs_meds_core_part_1047.parquet
ahs_meds_core_part_0081.parquet     ahs_meds_core_part_1048.parquet
ahs_meds_core_part_0082.parquet     ahs_meds_core_part_1049.parquet
ahs_meds_core_part_0083.parquet     ahs_meds_core_part_1050.parquet
ahs_meds_core_part_0084.parquet     ahs_meds_core_part_1051.parquet
ahs_meds_core_part_0085.parquet     ahs_meds_core_part_1052.parquet
ahs_meds_core_part_0086.parquet     ahs_meds_core_part_1053.parquet
ahs_meds_core_part_0087.parquet     ahs_meds_core_part_1054.parquet
ahs_meds_core_part_0088.parquet     ahs_meds_core_part_1055.parquet
ahs_meds_core_part_0089.parquet     ahs_meds_core_part_1056.parquet
ahs_meds_core_part_0090.parquet     ahs_meds_core_part_1057.parquet
ahs_meds_core_part_0091.parquet     ahs_meds_core_part_1058.parquet
ahs_meds_core_part_0092.parquet     ahs_meds_core_part_1059.parquet
ahs_meds_core_part_0093.parquet     ahs_meds_core_part_1060.parquet
ahs_meds_core_part_0094.parquet     ahs_meds_core_part_1061.parquet
ahs_meds_core_part_0095.parquet     ahs_meds_core_part_1062.parquet
ahs_meds_core_part_0096.parquet     ahs_meds_core_part_1063.parquet
ahs_meds_core_part_0097.parquet     ahs_meds_core_part_1064.parquet
ahs_meds_core_part_0098.parquet     ahs_meds_core_part_1065.parquet
ahs_meds_core_part_0099.parquet     ahs_meds_core_part_1066.parquet
ahs_meds_core_part_0100.parquet     ahs_meds_core_part_1067.parquet
ahs_meds_core_part_0101.parquet     ahs_meds_core_part_1068.parquet
ahs_meds_core_part_0102.parquet     ahs_meds_core_part_1069.parquet
ahs_meds_core_part_0103.parquet     ahs_meds_core_part_1070.parquet
ahs_meds_core_part_0104.parquet     ahs_meds_core_part_1071.parquet
ahs_meds_core_part_0105.parquet     ahs_meds_core_part_1072.parquet
ahs_meds_core_part_0106.parquet     ahs_meds_core_part_1073.parquet
ahs_meds_core_part_0107.parquet     ahs_meds_core_part_1074.parquet
ahs_meds_core_part_0108.parquet     ahs_meds_core_part_1075.parquet
ahs_meds_core_part_0109.parquet     ahs_meds_core_part_1076.parquet
ahs_meds_core_part_0110.parquet     ahs_meds_core_part_1077.parquet
ahs_meds_core_part_0111.parquet     ahs_meds_core_part_1078.parquet
ahs_meds_core_part_0112.parquet     ahs_meds_core_part_1079.parquet
ahs_meds_core_part_0113.parquet     ahs_meds_core_part_1080.parquet
ahs_meds_core_part_0114.parquet     ahs_meds_core_part_1081.parquet
ahs_meds_core_part_0115.parquet     ahs_meds_core_part_1082.parquet
ahs_meds_core_part_0116.parquet     ahs_meds_core_part_1083.parquet
ahs_meds_core_part_0117.parquet     ahs_meds_core_part_1084.parquet
ahs_meds_core_part_0118.parquet     ahs_meds_core_part_1085.parquet
ahs_meds_core_part_0119.parquet     ahs_meds_core_part_1086.parquet
ahs_meds_core_part_0120.parquet     ahs_meds_core_part_1087.parquet
ahs_meds_core_part_0121.parquet     ahs_meds_core_part_1088.parquet
ahs_meds_core_part_0122.parquet     ahs_meds_core_part_1089.parquet
ahs_meds_core_part_0123.parquet     ahs_meds_core_part_1090.parquet
ahs_meds_core_part_0124.parquet     ahs_meds_core_part_1091.parquet
ahs_meds_core_part_0125.parquet     ahs_meds_core_part_1092.parquet
ahs_meds_core_part_0126.parquet     ahs_meds_core_part_1093.parquet
ahs_meds_core_part_0127.parquet     ahs_meds_core_part_1094.parquet
ahs_meds_core_part_0128.parquet     ahs_meds_core_part_1095.parquet
ahs_meds_core_part_0129.parquet     ahs_meds_core_part_1096.parquet
ahs_meds_core_part_0130.parquet     ahs_meds_core_part_1097.parquet
ahs_meds_core_part_0131.parquet     ahs_meds_core_part_1098.parquet
ahs_meds_core_part_0132.parquet     ahs_meds_core_part_1099.parquet
ahs_meds_core_part_0133.parquet     ahs_meds_core_part_1100.parquet
ahs_meds_core_part_0134.parquet     ahs_meds_core_part_1101.parquet
ahs_meds_core_part_0135.parquet     ahs_meds_core_part_1102.parquet
ahs_meds_core_part_0136.parquet     ahs_meds_core_part_1103.parquet
ahs_meds_core_part_0137.parquet     ahs_meds_core_part_1104.parquet
ahs_meds_core_part_0138.parquet     ahs_meds_core_part_1105.parquet
ahs_meds_core_part_0139.parquet     ahs_meds_core_part_1106.parquet
ahs_meds_core_part_0140.parquet     ahs_meds_core_part_1107.parquet
ahs_meds_core_part_0141.parquet     ahs_meds_core_part_1108.parquet
ahs_meds_core_part_0142.parquet     ahs_meds_core_part_1109.parquet
ahs_meds_core_part_0143.parquet     ahs_meds_core_part_1110.parquet
ahs_meds_core_part_0144.parquet     ahs_meds_core_part_1111.parquet
ahs_meds_core_part_0145.parquet     ahs_meds_core_part_1112.parquet
ahs_meds_core_part_0146.parquet     ahs_meds_core_part_1113.parquet
ahs_meds_core_part_0147.parquet     ahs_meds_core_part_1114.parquet
ahs_meds_core_part_0148.parquet     ahs_meds_core_part_1115.parquet
ahs_meds_core_part_0149.parquet     ahs_meds_core_part_1116.parquet
ahs_meds_core_part_0150.parquet     ahs_meds_core_part_1117.parquet
ahs_meds_core_part_0151.parquet     ahs_meds_core_part_1118.parquet
ahs_meds_core_part_0152.parquet     ahs_meds_core_part_1119.parquet
ahs_meds_core_part_0153.parquet     ahs_meds_core_part_1120.parquet
ahs_meds_core_part_0154.parquet     ahs_meds_core_part_1121.parquet
ahs_meds_core_part_0155.parquet     ahs_meds_core_part_1122.parquet
ahs_meds_core_part_0156.parquet     ahs_meds_core_part_1123.parquet
ahs_meds_core_part_0157.parquet     ahs_meds_core_part_1124.parquet
ahs_meds_core_part_0158.parquet     ahs_meds_core_part_1125.parquet
ahs_meds_core_part_0159.parquet     ahs_meds_core_part_1126.parquet
ahs_meds_core_part_0160.parquet     ahs_meds_core_part_1127.parquet
ahs_meds_core_part_0161.parquet     ahs_meds_core_part_1128.parquet
ahs_meds_core_part_0162.parquet     ahs_meds_core_part_1129.parquet
ahs_meds_core_part_0163.parquet     ahs_meds_core_part_1130.parquet
ahs_meds_core_part_0164.parquet     ahs_meds_core_part_1131.parquet
ahs_meds_core_part_0165.parquet     ahs_meds_core_part_1132.parquet
ahs_meds_core_part_0166.parquet     ahs_meds_core_part_1133.parquet
ahs_meds_core_part_0167.parquet     ahs_meds_core_part_1134.parquet
ahs_meds_core_part_0168.parquet     ahs_meds_core_part_1135.parquet
ahs_meds_core_part_0169.parquet     ahs_meds_core_part_1136.parquet
ahs_meds_core_part_0170.parquet     ahs_meds_core_part_1137.parquet
ahs_meds_core_part_0171.parquet     ahs_meds_core_part_1138.parquet
ahs_meds_core_part_0172.parquet     ahs_meds_core_part_1139.parquet
ahs_meds_core_part_0173.parquet     ahs_meds_core_part_1140.parquet
ahs_meds_core_part_0174.parquet     ahs_meds_core_part_1141.parquet
ahs_meds_core_part_0175.parquet     ahs_meds_core_part_1142.parquet
ahs_meds_core_part_0176.parquet     ahs_meds_core_part_1143.parquet
ahs_meds_core_part_0177.parquet     ahs_meds_core_part_1144.parquet
ahs_meds_core_part_0178.parquet     ahs_meds_core_part_1145.parquet
ahs_meds_core_part_0179.parquet     ahs_meds_core_part_1146.parquet
ahs_meds_core_part_0180.parquet     ahs_meds_core_part_1147.parquet
ahs_meds_core_part_0181.parquet     ahs_meds_core_part_1148.parquet
ahs_meds_core_part_0182.parquet     ahs_meds_core_part_1149.parquet
ahs_meds_core_part_0183.parquet     ahs_meds_core_part_1150.parquet
ahs_meds_core_part_0184.parquet     ahs_meds_core_part_1151.parquet
ahs_meds_core_part_0185.parquet     ahs_meds_core_part_1152.parquet
ahs_meds_core_part_0186.parquet     ahs_meds_core_part_1153.parquet
ahs_meds_core_part_0187.parquet     ahs_meds_core_part_1154.parquet
ahs_meds_core_part_0188.parquet     ahs_meds_core_part_1155.parquet
ahs_meds_core_part_0189.parquet     ahs_meds_core_part_1156.parquet
ahs_meds_core_part_0190.parquet     ahs_meds_core_part_1157.parquet
ahs_meds_core_part_0191.parquet     ahs_meds_core_part_1158.parquet
ahs_meds_core_part_0192.parquet     ahs_meds_core_part_1159.parquet
ahs_meds_core_part_0193.parquet     ahs_meds_core_part_1160.parquet
ahs_meds_core_part_0194.parquet     ahs_meds_core_part_1161.parquet
ahs_meds_core_part_0195.parquet     ahs_meds_core_part_1162.parquet
ahs_meds_core_part_0196.parquet     ahs_meds_core_part_1163.parquet
ahs_meds_core_part_0197.parquet     ahs_meds_core_part_1164.parquet
ahs_meds_core_part_0198.parquet     ahs_meds_core_part_1165.parquet
ahs_meds_core_part_0199.parquet     ahs_meds_core_part_1166.parquet
ahs_meds_core_part_0200.parquet     ahs_meds_core_part_1167.parquet
ahs_meds_core_part_0201.parquet     ahs_meds_core_part_1168.parquet
ahs_meds_core_part_0202.parquet     ahs_meds_core_part_1169.parquet
ahs_meds_core_part_0203.parquet     ahs_meds_core_part_1170.parquet
ahs_meds_core_part_0204.parquet     ahs_meds_core_part_1171.parquet
ahs_meds_core_part_0205.parquet     ahs_meds_core_part_1172.parquet
ahs_meds_core_part_0206.parquet     ahs_meds_core_part_1173.parquet
ahs_meds_core_part_0207.parquet     ahs_meds_core_part_1174.parquet
ahs_meds_core_part_0208.parquet     ahs_meds_core_part_1175.parquet
ahs_meds_core_part_0209.parquet     ahs_meds_core_part_1176.parquet
ahs_meds_core_part_0210.parquet     ahs_meds_core_part_1177.parquet
ahs_meds_core_part_0211.parquet     ahs_meds_core_part_1178.parquet
ahs_meds_core_part_0212.parquet     ahs_meds_core_part_1179.parquet
ahs_meds_core_part_0213.parquet     ahs_meds_core_part_1180.parquet
ahs_meds_core_part_0214.parquet     ahs_meds_core_part_1181.parquet
ahs_meds_core_part_0215.parquet     ahs_meds_core_part_1182.parquet
ahs_meds_core_part_0216.parquet     ahs_meds_core_part_1183.parquet
ahs_meds_core_part_0217.parquet     ahs_meds_core_part_1184.parquet
ahs_meds_core_part_0218.parquet     ahs_meds_core_part_1185.parquet
ahs_meds_core_part_0219.parquet     ahs_meds_core_part_1186.parquet
ahs_meds_core_part_0220.parquet     ahs_meds_core_part_1187.parquet
ahs_meds_core_part_0221.parquet     ahs_meds_core_part_1188.parquet
ahs_meds_core_part_0222.parquet     ahs_meds_core_part_1189.parquet
ahs_meds_core_part_0223.parquet     ahs_meds_core_part_1190.parquet
ahs_meds_core_part_0224.parquet     ahs_meds_core_part_1191.parquet
ahs_meds_core_part_0225.parquet     ahs_meds_core_part_1192.parquet
ahs_meds_core_part_0226.parquet     ahs_meds_core_part_1193.parquet
ahs_meds_core_part_0227.parquet     ahs_meds_core_part_1194.parquet
ahs_meds_core_part_0228.parquet     ahs_meds_core_part_1195.parquet
ahs_meds_core_part_0229.parquet     ahs_meds_core_part_1196.parquet
ahs_meds_core_part_0230.parquet     ahs_meds_core_part_1197.parquet
ahs_meds_core_part_0231.parquet     ahs_meds_core_part_1198.parquet
ahs_meds_core_part_0232.parquet     ahs_meds_core_part_1199.parquet
ahs_meds_core_part_0233.parquet     ahs_meds_core_part_1200.parquet
ahs_meds_core_part_0234.parquet     ahs_meds_core_part_1201.parquet
ahs_meds_core_part_0235.parquet     ahs_meds_core_part_1202.parquet
ahs_meds_core_part_0236.parquet     ahs_meds_core_part_1203.parquet
ahs_meds_core_part_0237.parquet     ahs_meds_core_part_1204.parquet
ahs_meds_core_part_0238.parquet     ahs_meds_core_part_1205.parquet
ahs_meds_core_part_0239.parquet     ahs_meds_core_part_1206.parquet
ahs_meds_core_part_0240.parquet     ahs_meds_core_part_1207.parquet
ahs_meds_core_part_0241.parquet     ahs_meds_core_part_1208.parquet
ahs_meds_core_part_0242.parquet     ahs_meds_core_part_1209.parquet
ahs_meds_core_part_0243.parquet     ahs_meds_core_part_1210.parquet
ahs_meds_core_part_0244.parquet     ahs_meds_core_part_1211.parquet
ahs_meds_core_part_0245.parquet     ahs_meds_core_part_1212.parquet
ahs_meds_core_part_0246.parquet     ahs_meds_core_part_1213.parquet
ahs_meds_core_part_0247.parquet     ahs_meds_core_part_1214.parquet
ahs_meds_core_part_0248.parquet     ahs_meds_core_part_1215.parquet
ahs_meds_core_part_0249.parquet     ahs_meds_core_part_1216.parquet
ahs_meds_core_part_0250.parquet     ahs_meds_core_part_1217.parquet
ahs_meds_core_part_0251.parquet     ahs_meds_core_part_1218.parquet
ahs_meds_core_part_0252.parquet     ahs_meds_core_part_1219.parquet
ahs_meds_core_part_0253.parquet     ahs_meds_core_part_1220.parquet
ahs_meds_core_part_0254.parquet     ahs_meds_core_part_1221.parquet
ahs_meds_core_part_0255.parquet     ahs_meds_core_part_1222.parquet
ahs_meds_core_part_0256.parquet     ahs_meds_core_part_1223.parquet
ahs_meds_core_part_0257.parquet     ahs_meds_core_part_1224.parquet
ahs_meds_core_part_0258.parquet     ahs_meds_core_part_1225.parquet
ahs_meds_core_part_0259.parquet     ahs_meds_core_part_1226.parquet
ahs_meds_core_part_0260.parquet     ahs_meds_core_part_1227.parquet
ahs_meds_core_part_0261.parquet     ahs_meds_core_part_1228.parquet
ahs_meds_core_part_0262.parquet     ahs_meds_core_part_1229.parquet
ahs_meds_core_part_0263.parquet     ahs_meds_core_part_1230.parquet
ahs_meds_core_part_0264.parquet     ahs_meds_core_part_1231.parquet
ahs_meds_core_part_0265.parquet     ahs_meds_core_part_1232.parquet
ahs_meds_core_part_0266.parquet     ahs_meds_core_part_1233.parquet
ahs_meds_core_part_0267.parquet     ahs_meds_core_part_1234.parquet
ahs_meds_core_part_0268.parquet     ahs_meds_core_part_1235.parquet
ahs_meds_core_part_0269.parquet     ahs_meds_core_part_1236.parquet
ahs_meds_core_part_0270.parquet     ahs_meds_core_part_1237.parquet
ahs_meds_core_part_0271.parquet     ahs_meds_core_part_1238.parquet
ahs_meds_core_part_0272.parquet     ahs_meds_core_part_1239.parquet
ahs_meds_core_part_0273.parquet     ahs_meds_core_part_1240.parquet
ahs_meds_core_part_0274.parquet     ahs_meds_core_part_1241.parquet
ahs_meds_core_part_0275.parquet     ahs_meds_core_part_1242.parquet
ahs_meds_core_part_0276.parquet     ahs_meds_core_part_1243.parquet
ahs_meds_core_part_0277.parquet     ahs_meds_core_part_1244.parquet
ahs_meds_core_part_0278.parquet     ahs_meds_core_part_1245.parquet
ahs_meds_core_part_0279.parquet     ahs_meds_core_part_1246.parquet
ahs_meds_core_part_0280.parquet     ahs_meds_core_part_1247.parquet
ahs_meds_core_part_0281.parquet     ahs_meds_core_part_1248.parquet
ahs_meds_core_part_0282.parquet     ahs_meds_core_part_1249.parquet
ahs_meds_core_part_0283.parquet     ahs_meds_core_part_1250.parquet
ahs_meds_core_part_0284.parquet     ahs_meds_core_part_1251.parquet
ahs_meds_core_part_0285.parquet     ahs_meds_core_part_1252.parquet
ahs_meds_core_part_0286.parquet     ahs_meds_core_part_1253.parquet

In [4]:
mimic = pd.read_parquet("/data/padmalab_external/special_project/meds_pipeline_output/mimic/mimic_ecg_hosp_ed_linkage.parquet")
mimic

,subject_id,study_id,ecg_time,hadm_id,hosp_start_time,hosp_end_time,stay_id,ed_start_time,ed_end_time
0,10000032,40689238,2180-07-23 08:44:00,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00
1,10000032,44458630,2180-07-23 09:54:00,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00
2,10000032,49036311,2180-08-06 09:07:00,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,<NA>,NaT,NaT
3,10000117,45090959,2181-03-04 17:14:00,<NA>,NaT,NaT,<NA>,NaT,NaT
4,10000117,48446569,2183-09-18 13:52:00,27988844,2183-09-18 18:10:00,2183-09-21 16:30:00,33176849,2183-09-18 08:41:00,2183-09-18 20:20:00
...,...,...,...,...,...,...,...,...,...
800036,19999840,48436051,2164-09-12 05:13:00,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,<NA>,NaT,NaT
800037,19999840,48683947,2164-09-12 12:28:00,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,<NA>,NaT,NaT
800038,19999987,41190887,2145-11-02 19:54:00,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00
800039,19999987,45828463,2145-11-03 03:00:00,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,<NA>,NaT,NaT
800040,19999987,49815090,2145-11-03 08:47:00,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,<NA>,NaT,NaT

In [6]:
# Phase 1: Inspect dad_df structure
print("dad_df shape:", dad_df.shape)
print("\ndad_df columns:")
print(dad_df.columns.tolist())
dad_df[['PATID', 'ADMITDATE_DT', 'DISDATE_DT', 'episode_order']].head(10)

dad_df shape: (1185365, 147)

dad_df columns:
['PATID', 'ADMITDATE_DT', 'DISDATE_DT', 'AGE_ADMIT', 'SEX', 'DXCODE1', 'DXCODE2', 'DXCODE3', 'DXCODE4', 'DXCODE5', 'DXCODE6', 'DXCODE7', 'DXCODE8', 'DXCODE9', 'DXCODE10', 'DXCODE11', 'DXCODE12', 'DXCODE13', 'DXCODE14', 'DXCODE15', 'DXCODE16', 'DXCODE17', 'DXCODE18', 'DXCODE19', 'DXCODE20', 'DXCODE21', 'DXCODE22', 'DXCODE23', 'DXCODE24', 'DXCODE25', 'DXPREF1', 'DXPREF2', 'DXPREF3', 'DXPREF4', 'DXPREF5', 'DXPREF6', 'DXPREF7', 'DXPREF8', 'DXPREF9', 'DXPREF10', 'DXPREF11', 'DXPREF12', 'DXPREF13', 'DXPREF14', 'DXPREF15', 'DXPREF16', 'DXPREF17', 'DXPREF18', 'DXPREF19', 'DXPREF20', 'DXPREF21', 'DXPREF22', 'DXPREF23', 'DXPREF24', 'DXPREF25', 'DXTYPE1', 'DXTYPE2', 'DXTYPE3', 'DXTYPE4', 'DXTYPE5', 'DXTYPE6', 'DXTYPE7', 'DXTYPE8', 'DXTYPE9', 'DXTYPE10', 'DXTYPE11', 'DXTYPE12', 'DXTYPE13', 'DXTYPE14', 'DXTYPE15', 'DXTYPE16', 'DXTYPE17', 'DXTYPE18', 'DXTYPE19', 'DXTYPE20', 'DXTYPE21', 'DXTYPE22', 'DXTYPE23', 'DXTYPE24', 'DXTYPE25', 'DOCSVC1', 'ADMITBYAMB', 'ADMITCAT', 'DISP', 'MPSERV', 'RIW', 'ELOS', 'SCU1', 'SCU2', 'SCU3', 'SCU4', 'SCU5', 'SCU6', 'SCUADMDT1_DT', 'SCUADMDT2_DT', 'SCUADMDT3_DT', 'SCUADMDT4_DT', 'SCUADMDT5_DT', 'SCUADMDT6_DT', 'SCUDISDT1_DT', 'SCUDISDT2_DT', 'SCUDISDT3_DT', 'SCUDISDT4_DT', 'SCUDISDT5_DT', 'SCUDISDT6_DT', 'INST', 'PROCCODE1', 'PROCCODE2', 'PROCCODE3', 'PROCCODE4', 'PROCCODE5', 'PROCCODE6', 'PROCCODE7', 'PROCCODE8', 'PROCCODE9', 'PROCCODE10', 'PROCCODE11', 'PROCCODE12', 'PROCCODE13', 'PROCCODE14', 'PROCCODE15', 'PROCCODE16', 'PROCCODE17', 'PROCCODE18', 'PROCCODE19', 'PROCCODE20', 'PROCSVC1', 'PROCSVC2', 'PROCSVC3', 'PROCSVC4', 'PROCSVC5', 'PROCSVC6', 'PROCSVC7', 'PROCSVC8', 'PROCSVC9', 'PROCSVC10', 'PROCSVC11', 'PROCSVC12', 'PROCSVC13', 'PROCSVC14', 'PROCSVC15', 'PROCSVC16', 'PROCSVC17', 'PROCSVC18', 'PROCSVC19', 'PROCSVC20', 'episode_order']

    PATID ADMITDATE_DT DISDATE_DT episode_order
0   58086   2021-08-05 2021-08-17      58086_13
1   36014   2021-07-17 2021-08-20       36014_3
2   37173   2021-08-21 2021-08-21      37173_22
3   81034   2021-08-13 2021-08-19       81034_8
4  124980   2021-08-20 2021-08-21     124980_15
5  155776   2021-05-14 2021-08-18      155776_4
6  143583   2021-08-15 2021-08-16     143583_22
7  182090   2021-08-14 2021-08-21     182090_14
8  160575   2021-07-16 2021-08-20      160575_8
9   23585   2021-08-27 2021-09-09      23585_16

In [7]:
# Phase 2: Check episode_order uniqueness in dad_df and ed_df
for name, df in [('dad_df', dad_df), ('ed_df', ed_df)]:
    total = len(df)
    unique_ep = df['episode_order'].nunique()
    print(f"{name}:")
    print(f"  Total rows:              {total:>10,}")
    print(f"  Unique episode_orders:   {unique_ep:>10,}")
    print(f"  Duplicate rows:          {total - unique_ep:>10,}")
    print(f"  Is unique: {df['episode_order'].is_unique}")
    print()

dad_df:
  Total rows:               1,185,365
  Unique episode_orders:    1,017,576
  Duplicate rows:             167,789
  Is unique: False

ed_df:
  Total rows:               3,734,775
  Unique episode_orders:    3,152,746
  Duplicate rows:             582,029
  Is unique: False

In [8]:
# Phase 3: Main merge — ecg + dad (inpatient) + ed (emergency)
dad_slim = dad_df[['episode_order', 'ADMITDATE_DT', 'DISDATE_DT']].copy()
ed_slim  = ed_df[['episode_order', 'VISIT_DATE_DT']].copy()
ecg_base = ecg_df[['patient_id', 'ecg_id', 'ecg_acquisition_time', 'episode_id']].copy()

print(f"ecg_base:  {ecg_base.shape}")
print(f"  ECGs with episode_id:    {ecg_base['episode_id'].notna().sum():>10,}")
print(f"  ECGs without episode_id: {ecg_base['episode_id'].isna().sum():>10,}")

# Left join with DAD (inpatient: ADMITDATE_DT, DISDATE_DT)
merged = ecg_base.merge(
    dad_slim,
    left_on='episode_id',
    right_on='episode_order',
    how='left'
).drop(columns='episode_order')
print(f"\nAfter DAD merge:  {merged.shape}  (fan-out: +{len(merged) - len(ecg_base):,} rows)")

# Left join with ED (emergency: VISIT_DATE_DT)
merged = merged.merge(
    ed_slim,
    left_on='episode_id',
    right_on='episode_order',
    how='left'
).drop(columns='episode_order')
print(f"After ED  merge:  {merged.shape}  (fan-out: +{len(merged) - len(ecg_base):,} rows total)")

ecg_base:  (2257525, 4)
  ECGs with episode_id:     1,780,856
  ECGs without episode_id:    476,669

After DAD merge:  (2698415, 6)  (fan-out: +440,890 rows)
After ED  merge:  (3399364, 7)  (fan-out: +1,141,839 rows total)

In [9]:
# Phase 4: Deduplication — keep row nearest in time to ecg_acquisition_time
n_before = len(merged)
if n_before > len(ecg_base):
    ecg_t    = pd.to_datetime(merged['ecg_acquisition_time'])
    admit_dt = pd.to_datetime(merged['ADMITDATE_DT'], errors='coerce')
    visit_dt = pd.to_datetime(merged['VISIT_DATE_DT'], errors='coerce')

    # Time diff to each available date; take whichever is smaller
    dad_diff = (admit_dt - ecg_t).abs()
    ed_diff  = (visit_dt - ecg_t).abs()
    merged['_time_diff'] = pd.concat([dad_diff, ed_diff], axis=1).min(axis=1, skipna=True)
    merged['_time_diff'] = merged['_time_diff'].fillna(pd.Timedelta(0))  # no episode rows

    merged = (merged
              .sort_values(['ecg_id', '_time_diff'])
              .drop_duplicates(subset='ecg_id', keep='first')
              .drop(columns='_time_diff')
              .reset_index(drop=True))

    print(f"Rows before dedup: {n_before:,}")
    print(f"Rows after  dedup: {len(merged):,}  (removed {n_before - len(merged):,} duplicate rows)")
else:
    merged = merged.reset_index(drop=True)
    print("No fan-out detected — deduplication not needed.")

Rows before dedup: 3,399,364
Rows after  dedup: 2,257,525  (removed 1,141,839 duplicate rows)

In [10]:
# Phase 5: Final AHS ECG-Episode linkage table
ahs_linkage = merged[['patient_id', 'ecg_id', 'ecg_acquisition_time', 'episode_id',
                       'ADMITDATE_DT', 'DISDATE_DT', 'VISIT_DATE_DT']].copy()

print("=" * 55)
print("  AHS ECG–Episode Linkage Table")
print("=" * 55)
print(f"  Total ECGs                    : {len(ahs_linkage):>10,}")
print(f"  ECGs with any episode_id      : {ahs_linkage['episode_id'].notna().sum():>10,}")
print(f"  Linked to DAD (inpatient)     : {ahs_linkage['ADMITDATE_DT'].notna().sum():>10,}")
print(f"  Linked to ED                  : {ahs_linkage['VISIT_DATE_DT'].notna().sum():>10,}")
print(f"  Linked to both DAD + ED       : {(ahs_linkage['ADMITDATE_DT'].notna() & ahs_linkage['VISIT_DATE_DT'].notna()).sum():>10,}")
print(f"  No episode (unlinked)         : {ahs_linkage['episode_id'].isna().sum():>10,}")
print("=" * 55)

ahs_linkage

=======================================================
  AHS ECG–Episode Linkage Table
=======================================================
  Total ECGs                    :  2,257,525
  ECGs with any episode_id      :  1,780,856
  Linked to DAD (inpatient)     :  1,412,268
  Linked to ED                  :  1,538,943
  Linked to both DAD + ED       :  1,170,355
  No episode (unlinked)         :    476,669
=======================================================

,patient_id,ecg_id,ecg_acquisition_time,episode_id,ADMITDATE_DT,DISDATE_DT,VISIT_DATE_DT
0,284115,00000100-6146-11e8-4823-0012119a0029,2018-05-26 18:30:32,284115_6,2018-05-26,2018-05-29,2018-05-26
1,215043,00000980-0d09-11e2-4823-0030ad3f0029,2012-10-02 20:12:21,215043_24,2012-10-02,2012-10-18,2012-09-29
2,233825,00000c00-1e8b-11e0-4823-00a6af060029,2011-01-12 13:25:45,None,NaT,NaT,NaT
3,252402,00001280-340f-11e3-4823-010d8afe0029,2013-10-13 07:48:34,252402_1,2013-10-12,2013-10-15,2013-10-12
4,239622,00001a80-775f-11e8-4823-006d86790029,2018-06-23 21:24:58,239622_1,NaT,NaT,2018-06-23
...,...,...,...,...,...,...,...
2257520,222030,fffff480-8053-11e8-4823-0018d0460029,2018-07-05 06:58:52,222030_3,2018-06-25,2018-07-22,2018-06-25
2257521,192153,fffff480-8a72-11e2-4823-008bb09b0029,2013-03-11 10:36:04,None,NaT,NaT,NaT
2257522,103672,fffff680-9ffa-11e8-4823-000671930029,2018-08-14 13:42:22,103672_117,2018-08-08,2018-08-14,2018-08-08
2257523,230816,fffff900-4f22-11e4-4823-0039d0eb0029,2014-10-08 12:34:48,230816_2,2014-10-08,2014-10-19,2014-10-08
2257524,90867,fffffa00-9f51-11dc-4823-012925e50029,2007-11-30 07:33:02,90867_10,2007-11-30,2007-12-01,2007-11-29

In [13]:
ahs_linkage.to_parquet("/data/padmalab_external/special_project/meds_pipeline_output/ahs/ahs_ecg_hosp_ed_linkage.parquet", index=False)